apiVersion: 1
providers:
  - name: 'dashboards'
    orgId: 1
    folder: ''
    folderUid: ''
    type: file
    disableDeletion: true
    updateIntervalSeconds: 5
    options:
      path: /var/lib/grafana/dashboards
